#!/usr/bin/env bash

\cp .cache/$@.json .cache/data.json 2> /dev/null # leading \ to unalias cp
rm kb.config.json 2> /dev/null
ln -s $@.kb.config.json kb.config.json
yarn
yarn go
\cp .cache/data.json .cache/$@.json 2> /dev/null

